# Generated by Django 5.1.6 on 2025-03-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_newqueryinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newqueryinfo',
            old_name='name',
            new_name='username',
        ),
    ]
