# Generated by Django 5.1.6 on 2025-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_rename_name_newqueryinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newqueryinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
